### ISSUE TITLE
jayram@ubuntu:~/sadit$ ./cmdsadit detect -c ./Example/DetectSQLConfig.py -d ./test/n0_flow.txt --method='mfmb' --pic_show fails

### ISSUE THREAD

**Issue by hbhzwj** [hbhzwj/SADIT#7]
jayram@ubuntu:~/sadit$ ./cmdsadit detect -c ./Example/DetectSQLConfig.py -d ./test/n0_flow.txt --method='mfmb' --pic_show
[warning] socketIO_client is not found. Real-time ability is disabled
--> Use [matplotlib] as plot backend
--> [warning] cannot import sql related function, reading for sql server is not supported
WARNING:util:Cannot find [socketIO_client], real-time ability is disabled.
WARNING:util:Cannot import sql related function, reading for sql server is not supported
Probabably you forgot to specify some options? run cmdsadit <exper> -h for more information.
Traceback (most recent call last):
  File "./cmdsadit", line 74, in main
    get_exper(args.experiment, res_args).run()
  File "/home/jayram/sadit/Detector/gad/Experiment/Detect.py", line 93, in run
    detector = self.detect()
  File "/home/jayram/sadit/Detector/gad/Experiment/Detect.py", line 89, in detect
    self.res_args)
  File "/home/jayram/sadit/Detector/gad/Detector/API.py", line 81, in detect
    data_file = data_map[ desc['data_type'] ](f_name, desc)
  File "/home/jayram/sadit/Detector/gad/Detector/Data.py", line 138, in __init__
    self._init()
  File "/home/jayram/sadit/Detector/gad/Detector/Data.py", line 262, in _init
    self._cluster_src_ip(fea_option['cluster'][0], self.unique_ip)
TypeError: 'int' object has no attribute '__getitem__'

**Comment by hbhzwj** [comment]
Duplicate of https://github.com/hbhzwj/SADIT/issues/6
