### ISSUE TITLE
./Example/DetectBatch.py fails

### ISSUE THREAD

**Issue by hbhzwj** [hbhzwj/SADIT#8]
jayram@ubuntu:~/sadit$ ./cmdsadit  detect -c ./Example/DetectBatch.py -d ./test/n0_flow.txt --method='mfmb' --pic_show
[warning] socketIO_client is not found. Real-time ability is disabled
--> Use [matplotlib] as plot backend
--> [warning] cannot import sql related function, reading for sql server is not supported
WARNING:util:Cannot find [socketIO_client], real-time ability is disabled.
WARNING:util:Cannot import sql related function, reading for sql server is not supported
Probabably you forgot to specify some options? run cmdsadit <exper> -h for more information.
Traceback (most recent call last):
  File "./cmdsadit", line 74, in main
    get_exper(args.experiment, res_args).run()
  File "./cmdsadit", line 52, in get_exper
    exper = getattr(Experiment, exper_name.lower())(argv)
  File "/home/jayram/sadit/Detector/gad/Experiment/Detect.py", line 14, in __init__
    super(Detect, self).__init__(argv, parser)
  File "/home/jayram/sadit/Detector/gad/Experiment/BaseExper.py", line 24, in __init__
    self.args, self.res_args = parser.parse_known_args(argv)
  File "/usr/lib/python2.7/argparse.py", line 1720, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python2.7/argparse.py", line 1926, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/lib/python2.7/argparse.py", line 1866, in consume_optional
    take_action(action, args, option_string)
  File "/usr/lib/python2.7/argparse.py", line 1778, in take_action
    argument_values = self._get_values(action, argument_strings)
  File "/usr/lib/python2.7/argparse.py", line 2204, in _get_values
    value = self._get_value(action, arg_string)
  File "/usr/lib/python2.7/argparse.py", line 2233, in _get_value
    result = type_func(arg_string)
  File "/home/jayram/sadit/Detector/gad/Experiment/BaseExper.py", line 49, in <lambda>
    type=lambda x: load_config(x),
  File "/home/jayram/sadit/Detector/gad/util/util.py", line 228, in load_config
    execfile(f_name, config)
IOError: [Errno 2] No such file or directory: './Example/DetectBatch.py'

**Comment by jingzbu** [comment]
Try this command:
```./cmdsadit detect -c ./Example/DetectBatchConfig.py -d ./test/n0_flow.txt --method='mfmb' --pic_show```
